### PR TITLE
fix: Fix where we move the pointer

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
I'm getting errors now on Chrome 75 like `MoveTargetOutOfBoundsError: move target out of bounds`.

**Review by jquense — APPROVED** [review]

**Comment by taion** [comment]
@itajaja Does this look right?

**Review by itajaja — COMMENTED** [review]
this is so hacky, no wonder it broke. I am not entirely sure it is actually needed for us, depends if we send to percy the DOM with hover states or not

**Comment by taion** [comment]
won't matter once we move to karma :p

**Comment by taion** [comment]
are you okay with this?

**Comment by itajaja** [comment]
sure

**Review by itajaja — APPROVED** [review]

**Comment by taion** [comment]
cc @sloria

Maybe we don't need this mouse move stuff at all if we're using Percy now.

**Comment by sloria** [comment]
Good to know. I just found out some of my previous usages of `.actions({bridge: true})` weren't really necessary with the latest updates to webdriver. But would be nice to get ride of the mouse stuff anyway.

**Pull request merged**
